# Generated by Django 4.2.1 on 2023-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zutat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='zutaten/')),
                ('beschreibung', models.TextField()),
                ('mindesthaltbarkeitsdatum', models.DateField()),
                ('anzahl', models.PositiveIntegerField()),
                ('rubrik', models.CharField(max_length=255)),
            ],
        ),
    ]
