# Generated by Django 4.2.1 on 2023-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_ingredient_delete_zutat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='tag',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tag',
            field=models.ManyToManyField(blank=True, to='page.tag'),
        ),
    ]
