# Generated by Django 4.2.1 on 2023-05-23 06:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('page', '0003_tag_remove_ingredient_tag_ingredient_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='tag',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
