# Generated by Django 4.2.1 on 2023-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_ingredient_tag_ingredient_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
