# Generated by Django 4.2.1 on 2023-06-07 09:21

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_ingredient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepy_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=page.models.upload_image)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=page.models.upload_image)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('recepy_steps', models.ManyToManyField(to='page.recepy_step')),
            ],
        ),
    ]
