# Generated by Django 4.2.1 on 2023-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_recepy_step_recepy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepy',
            name='ingredients',
            field=models.ManyToManyField(to='page.ingredient'),
        ),
        migrations.AddField(
            model_name='recepy_step',
            name='ingredients',
            field=models.ManyToManyField(to='page.ingredient'),
        ),
    ]
