# Generated by Django 4.2.1 on 2023-06-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_recepy_ingredients_recepy_step_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recepy',
            new_name='recipe',
        ),
        migrations.RenameModel(
            old_name='recepy_step',
            new_name='recipe_step',
        ),
    ]
