# Generated by Django 4.2.1 on 2023-06-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_rename_recepy_recipe_rename_recepy_step_recipe_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recepy_steps',
            new_name='recipe_steps',
        ),
    ]
