# Generated by Django 4.2.1 on 2023-06-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_rename_recepy_steps_recipe_recipe_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_step',
            old_name='description',
            new_name='recipe_step_description',
        ),
        migrations.RenameField(
            model_name='recipe_step',
            old_name='img',
            new_name='recipe_step_img',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe_step',
            name='ingredients',
        ),
    ]
