# Generated by Django 4.2.1 on 2023-06-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_rename_description_recipe_step_recipe_step_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_step',
            name='recipe_step_img',
        ),
    ]
