# Generated by Django 4.2.1 on 2023-06-07 11:21

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_recipe_step_recipe_step_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_step',
            name='recipe_step_img',
            field=models.ImageField(default=1, upload_to=page.models.upload_image),
            preserve_default=False,
        ),
    ]
