# Generated by Django 4.2.1 on 2023-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_recipe_step_recipe_step_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='part_of_recipe',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='page.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe_step',
            name='recipe_step_ingredients',
            field=models.ManyToManyField(to='page.ingredient'),
        ),
    ]
