# Generated by Django 4.2.1 on 2023-06-08 11:14

from django.db import migrations, models
import page.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('page', '0013_ingredient_part_of_recipe_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=page.models.upload_image),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='mhd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
